# Generated by Django 2.2.6 on 2020-03-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.FloatField(default=0.0),
        ),
    ]
