# Generated by Django 2.2.6 on 2019-10-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_history',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='orders',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='order_details_history',
        ),
        migrations.DeleteModel(
            name='order_history',
        ),
    ]
