# Generated by Django 3.0 on 2020-06-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('order', '0002_auto_20200610_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='features',
            field=models.ManyToManyField(blank=True, to='products.productfeatures'),
        ),
    ]
