# Generated by Django 3.0.8 on 2020-07-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_wishlist_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='items',
            field=models.ManyToManyField(to='order.wishlistdetails'),
        ),
    ]
