# Generated by Django 2.2.6 on 2019-10-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191015_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='items',
            field=models.ManyToManyField(to='order.order_details'),
        ),
    ]
