# Generated by Django 2.2.6 on 2019-10-15 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20191015_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.branch_products'),
        ),
    ]
