# Generated by Django 3.0 on 2019-12-21 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20191211_1607'),
        ('order', '0007_review_wishlist_wishlistdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
