# Generated by Django 2.2.6 on 2019-12-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_review_wishlist_wishlistdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
