# Generated by Django 3.0 on 2019-12-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20191221_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
