# Generated by Django 2.2.6 on 2020-03-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20191226_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
