# Generated by Django 3.0 on 2019-12-23 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20191221_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='total_price',
        ),
    ]
