# Generated by Django 3.0 on 2020-04-10 02:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_orders_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 2, 34, 38, 925196, tzinfo=utc)),
        ),
    ]
