# Generated by Django 3.0 on 2020-04-10 02:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20200410_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 2, 35, 40, 475594, tzinfo=utc)),
        ),
    ]
