# Generated by Django 3.0 on 2020-04-15 09:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20200414_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 9, 30, 43, 654724, tzinfo=utc)),
        ),
    ]
