# Generated by Django 2.2.6 on 2019-10-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191013_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prev_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
