# Generated by Django 3.0 on 2020-06-27 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brands',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.brand_name'),
        ),
    ]
