# Generated by Django 3.0.8 on 2020-07-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='whitelisted',
            field=models.BooleanField(default=False),
        ),
    ]
