# Generated by Django 2.2.6 on 2019-10-14 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_branch_products_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_products',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.branch'),
        ),
    ]
