# Generated by Django 3.0.8 on 2020-07-21 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_products_whitelisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brands',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand_name'),
        ),
    ]
