# Generated by Django 2.2.6 on 2019-10-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20191014_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='QR_code',
            new_name='name',
        ),
    ]
