# Generated by Django 2.2.6 on 2019-10-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20191015_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='QR_code',
            field=models.CharField(max_length=233),
        ),
    ]
