# Generated by Django 2.2.6 on 2020-01-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(default=100.0, max_length=20),
        ),
    ]
