# Generated by Django 2.2.6 on 2020-03-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200303_1808'),
        ('products', '0017_auto_20200206_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featurename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='productfeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(max_length=100)),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.features')),
            ],
            options={
                'unique_together': {('feat', 'values')},
            },
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=100),
        ),
        migrations.DeleteModel(
            name='branch_products',
        ),
        migrations.AddField(
            model_name='features',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.AlterUniqueTogether(
            name='features',
            unique_together={('product', 'featurename')},
        ),
    ]
