# Generated by Django 2.2.6 on 2020-03-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200303_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
