# Generated by Django 2.2.6 on 2020-03-03 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='branch',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='products.branch'),
            preserve_default=False,
        ),
    ]
