# Generated by Django 3.0 on 2020-04-06 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_products_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
    ]
