# Generated by Django 3.0 on 2020-04-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200410_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='QR_code',
            field=models.CharField(default='QR CODE WILL BE GENERATED AUTOMATICALLY', max_length=233),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
