# Generated by Django 3.0 on 2020-04-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20200410_0539'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('name', 'branch')},
        ),
    ]
