# Generated by Django 3.0 on 2020-04-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20200410_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Barcode',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
