# Generated by Django 3.0 on 2020-05-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20200513_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Barcode',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
