# Generated by Django 3.0 on 2020-05-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_limited_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='limited_offers',
            name='new_price',
            field=models.FloatField(default=0.0),
        ),
    ]
